routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});
Route::get('/angular', function () {
    return view('index_angular');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('user', 'UserController');
Route::resource('empresa', 'EmpresaController');
Route::resource('empresa_user', 'EmpresaUserController');

resources/views/index.blade.php
@extends('layouts.app', ["current" => "home"])

@section('body')
  <div class="jumbotron bg-light border border-secondary">
      <h5 class="card-title">Desafio BRy Tecnologia</h5>
      <!--
          Havia entendido errado a proposta. Como não havia tempo viável,
          fiz um redirecionamento para desenvolvero possível da aplicação em angular,
          mas mantendo a aplicação inicial.
      -->
      <p class="card=text">Estamos atualizando essa aplicação para Angular!</p><a class="nav-link" href="/angular">Clique Aqui para Visualizar</a>

  </div>

@endsection

resources/views/index_angular.blade.php
<!doctype html>
<html lang="{{app()->getLocale()}}">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>
  <body>
    <app-root></app-root>
    <script src="{{asset('js/runtime-es2015.js')}}" type="module"></script>
    <script src="{{asset('js/polyfills-es2015.js')}}" type="module">
    </script><script src="{{asset('js/runtime-es5.js')}}" nomodule defer>
    </script><script src="{{asset('js/polyfills-es5.js')}}" nomodule defer></script>
    <script src="{{asset('js/styles-es2015.js')}}" type="module"></script>
    <script src="{{asset('js/styles-es5.js')}}" nomodule defer></script>
    <script src="{{asset('js/vendor-es2015.js')}}" type="module"></script>
    <script src="{{asset('js/main-es2015.js')}}" type="module"></script>
    <script src="{{asset('js/vendor-es5.js')}}" nomodule defer></script>
    <script src="{{asset('js/main-es5.js')}}" nomodule defer></script>
  </body>
</html>

resources/views/navbar.blade.php
<!-- Barra de Navegação com Menus-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbar">
    <ul class="navbar-nav mr-auto">
      <li @if ($current=="home") class="nav-item active" @else class="nav-item" @endif>
        <a class="nav-link" href="/">Home</a>
      </li>
      <li @if ($current=="users") class="nav-item active" @else class="nav-item" @endif>
        <a class="nav-link" href="{{route('user.index')}}">Usuarios</a>
      </li>
      <li @if ($current=="empresas") class="nav-item active" @else class="nav-item" @endif>
        <a class="nav-link" href="{{route('empresa.index')}}">Empresas</a>
      </li>
    </ul>
  </div>
</nav>