routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});
Route::get('/angular', function () {
    return view('index_angular');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('user', 'UserController');
Route::resource('empresa', 'EmpresaController');
Route::resource('empresa_user', 'EmpresaUserController');

app/Empresa.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Empresa extends Model
{
    protected $fillable = [
        'name','cnpj','endereco',
    ];

    public function users () {
        return $this->belongsToMany('App\User', 'empresa_users');
    }

}

app/Http/Controllers/EmpresaController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Empresa;
use App\EmpresaUser;

use Illuminate\Http\Request;

class EmpresaController extends Controller
{

  public function index()
  {
      $Empresa = Empresa::orderBy('name','asc')->get();
      return view('empresa.index', ['Empresa' => $Empresa]);
  }

  public function create()
  {
      $User = User::get();
      return view ('empresa.create', ['User' => $User]);
  }


  public function store(Request $request)
  {
      $rules = [
          'name' => 'required',
          'cnpj' => 'required|digits:14|numeric|unique:empresas',
      ];
      $messages = [
          'required' => ':attribute é obrigatório',
          'digits' => 'caractéres de :attribute não são válidos',
          'numeric' => ':attribute deve conter apenas números',
          'unique' => ':attribute já existe no sistema',
      ];
      $request->validate($rules,$messages);
      $Empresa = new Empresa($request->all());
      $Empresa->save();
      $user_id = $request->get('user_id');
      foreach ($user_id as $usr_id)
      {
        $EmpresaUser = New EmpresaUser;
        $EmpresaUser->empresa_id = $Empresa->id;
        $EmpresaUser->user_id = $usr_id;
        $EmpresaUser->save();
      }
      return redirect()->route('empresa.index');
  }

  public function show($id)
  {
    $Empresa = Empresa::find($id);
    return view('empresa.show', ['Empresa' => $Empresa]);
  }

  public function edit($id)
  {
      $Empresa = Empresa::find($id);
      return view('empresa.edit',['Empresa' => $Empresa]);
  }

  public function update(Request $request, $id)
  {
      $rules = [
          'name' => 'required',
          'cnpj' => 'required|digits:14|numeric',
      ];
      $messages = [
          'required' => ':attribute é obrigatório',
          'digits' => 'caractéres de :attribute não são válidos',
          'numeric' => ':attribute deve conter apenas números',
          'unique' => ':attribute já existe no sistema',
      ];
      $request->validate($rules,$messages);
      $Empresa = Empresa::find($id)->update($request->all());
      return redirect()->route('empresa.index');
  }

  public function destroy($id)
  {
      $Empresa = Empresa::find($id);
      if (isset($Empresa)) {
        $Empresa->delete();
        return response ('OK', 200);
      }
      return response ('Não foi possível excluir o produto', 404);
  }

}

resources/views/empresa/create.blade.php
@extends('layouts.app', ["current" => "empresas"])
@section('body')
<div class="card border">
  <div class="card-body">
    <form class="form-horizontal" method="POST" action="{{ route('empresa.store') }}">
      @csrf
      <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
        <label for="name" class="col-md-4 control-label">Nome </label>
        <div class="col-md-6">
          <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required>
          @if ($errors->has('name'))
            <span class="help-block">
              <strong>{{ $errors->first('name') }}</strong>
            </span>
          @endif
        </div>
      </div>
      <div class="form-group{{ $errors->has('cnpj') ? ' has-error' : '' }}">
        <label for="cnpj" class="col-md-4 control-label">CNPJ </label>
        <div class="col-md-6">
          <input id="CNPJ" type="text" class="form-control" name="cnpj" value="{{ old('cnpj') }}" required>
          @if ($errors->has('cnpj'))
            <span class="help-block">
              <strong>{{ $errors->first('cnpj') }}</strong>
            </span>
          @endif
        </div>
      </div>
      <div class="form-group{{ $errors->has('endereco') ? ' has-error' : '' }}">
        <label for="endereco" class="col-md-4 control-label">Endereco </label>
        <div class="col-md-6">
          <input id="endereco" type="text" class="form-control" name="endereco" value="{{ old('endereco') }}">
          @if ($errors->has('endereco'))
            <span class="help-block">
              <strong>{{ $errors->first('endereco') }}</strong>
            </span>
            @endif
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-6 col-md-offset-4">
            <button type="submit" class="btn btn-primary">
              <i class="fa fa-save"></i> Salvar
            </button>
          </div>
        </div>
    </form>
  </div>
</div>
@endsection

resources/views/empresa/edit.blade.php
@extends('layouts.app', ["current" => "empresas"])
@section('body')
<div class="card border">
  <div class="card-body">
    <form class="form-horizontal" method="POST" action="{{ route('empresa.update',$Empresa->id) }}">
      @csrf
      @method('PUT')
      <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
        <label for="name" class="col-md-4 control-label">Nome </label>
        <div class="col-md-6">
          <input id="name" type="text" class="form-control" name="name" value="{{$Empresa->name}}" required>
          @if ($errors->has('name'))
            <span class="help-block">
              <strong>{{ $errors->first('name') }}</strong>
            </span>
          @endif
        </div>
      </div>
      <div class="form-group{{ $errors->has('cnpj') ? ' has-error' : '' }}">
        <label for="cnpj" class="col-md-4 control-label">CNPJ </label>
        <div class="col-md-6">
          <input id="CNPJ" type="text" class="form-control" name="cnpj" value="{{$Empresa->cnpj}}" required>
          @if ($errors->has('cnpj'))
            <span class="help-block">
              <strong>{{ $errors->first('cnpj') }}</strong>
            </span>
          @endif
        </div>
      </div>
      <div class="form-group{{ $errors->has('endereco') ? ' has-error' : '' }}">
        <label for="descricao" class="col-md-4 control-label">Endereco </label>
        <div class="col-md-6">
          <input id="endereco" type="text" class="form-control" name="endereco" value="{{$Empresa->endereco}}">
          @if ($errors->has('endereco'))
            <span class="help-block">
              <strong>{{ $errors->first('endereco') }}</strong>
            </span>
          @endif
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-6 col-md-offset-4">
          <button type="submit" class="btn btn-primary">
            <i class="fa fa-save"></i> Salvar
          </button>
        </div>
      </div>
    </form>
  </div>
</div>
@endsection

resources/views/empresa/index.blade.php
@extends('layouts.app', ["current" => "empresas"])
@section('body')
<div class="card border">
  <div class="card-body">
    <h5 class="card-title">Empresas Cadastradas</h5>
    <div class="table-responsive">
      <table class="table table-ordered table-hover">
        <tr>
          <th>Nome</th>
          <th>CNPJ</th>
          <th></th>
          <th></th>
          <th ></th>
        </tr>
        @foreach ($Empresa as $Empresa)
          <tr>
            <td> {{$Empresa->name}}</td>
            <td> {{$Empresa->cnpj}}</td>
            <td class="text-center">
              <a href= "{{ route('empresa.edit',$Empresa->id) }}" class="btn btn-sm">
                Editar</a>
            </td>
            <td class="text-center">
              <a href= "{{ route('empresa.show',$Empresa->id) }}" class="btn btn-sm">
                Informações</a>
            </td>
            <td class="text-center">
              {{method_field('DELETE')}}
              <a href= "{{ route('empresa.destroy',$Empresa->id) }}" value="Delete" class="btn btn-sm">
              Excluir</a>
            </td>
          </tr>
        @endforeach
      </table>
      <a class="btn btn-danger" href="{{ route('empresa.create') }}">Cadastrar Nova Empresa</a>
    </div>
  </div>
</div>
@endsection
@section('javascript')
  <script type="text/javascript">

  </script>
@endsection

resources/views/empresa/show.blade.php
@extends('layouts.app', ["current" => "empresas"])
@section('body')
<div class="card border">
  <div class="card-body">
    <h5 class="card-title">Dados da Empresa</h5>
    <form class="form-horizontal" role="form" method="POST" action="#">
      <div class="form-group">
        <label for="user" class="col-md-4 control-label">Razão Social (Nome)</label>
        <label for="user" class="col-md-6 control-label text-left">{{ $Empresa->name }}</label>
      </div>
      <div class="form-group">
        <label for="nome" class="col-md-4 control-label">CNPJ</label>
        <label for="nome" class="col-md-6 control-label text-left">{{ $Empresa->cnpj }}</label>
      </div>
      <div class="form-group">
        <label for="nome" class="col-md-4 control-label">Endereço</label>
        <label for="nome" class="col-md-6 control-label text-left">{{ $Empresa->endereco }}</label>
      </div>
    </form>
  </div>
</div>
@endsection