routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});
Route::get('/angular', function () {
    return view('index_angular');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('user', 'UserController');
Route::resource('empresa', 'EmpresaController');
Route::resource('empresa_user', 'EmpresaUserController');

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class User extends Model
{
    protected $fillable = [
        'name','cpf','login','email','endereco',
    ];

    public function empresas () {
        return $this->belongsToMany('App\Empresa', 'empresa_users');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;
use App\User;
use App\Empresa;
use App\EmpresaUser;
use DB;
use Illuminate\Http\Request;

class UserController extends Controller
{

  public function index()
  {
      $User = User::orderBy('name','asc')->get();
      return view('user.index', ['User' => $User]);
  }

  public function create()
  {
      $Empresa = Empresa::get();
      return view ('user.create', ['Empresa' => $Empresa]);
  }


  public function store(Request $request)
  {
      // Criar regras de validação básicas.
      $rules = [
          'name' => 'required',
          'cpf' => 'required|digits:11|numeric|unique:users',
          'email' => 'required|email',
          'login' => 'required|unique:users',
      ];
      $messages = [
          'required' => ':attribute é obrigatório',
          'digits' => 'caractéres de :attribute não são válidos',
          'numeric' => ':attribute deve conter apenas números',
          'unique' => ':attribute já existe no sistema',
      ];
      $request->validate($rules,$messages);
      $User = new User($request->all());
      $User->save();
      $empresa_id = $request->get('empresa_id');
      foreach ($empresa_id as $emp_id)
      {
        $EmpresaUser = New EmpresaUser;
        $EmpresaUser->empresa_id = $emp_id;
        $EmpresaUser->user_id = $User->id;
        $EmpresaUser->save();
      }
      return redirect()->route('user.index');
  }

  public function show($id)
  {
    //Get para Buscar dados de Empresa
    $User = User::find($id);
    return view('user.show', ['User' => $User]);

  }

  public function edit($id)
  {
    $User = User::find($id);
    $Empresa = Empresa::get();
    return view('user.edit',['User' => $User], ['Empresa' => $Empresa]);
  }

  public function update(Request $request, $id)
  {
      // Criar regras de validação básicas.
      $rules = [
          'name' => 'required',
          'cpf' => 'required|digits:11|numeric',
          'email' => 'required|email',
          'login' => 'required',
      ];
      $messages = [
          'required' => ':attribute é obrigatório',
          'digits' => 'caractéres de :attribute não são válidos',
          'numeric' => ':attribute deve conter apenas números',
          'unique' => ':attribute já existe no sistema',
          'email.email' => 'digite um email válido',
      ];
      $request->validate($rules,$messages);
      $User = User::find($id)->update($request->all());
      return redirect()->route('user.index');
  }

  public function destroy($id)
  {
      $User = User::find($id);
      if (isset($User)) {
        $User->delete();
        return response ('OK', 200);
      }
      return response ('Não foi possível excluir o produto', 404);
  }

}

resources/views/user/create.blade.php
@extends('layouts.app', ["current" => "users"])
@section('body')
<div class="card border">
  <div class="card-body">
    <form class="form-horizontal" role="form" method="POST" action="{{ route('user.store') }}">
      @csrf
      <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
        <label for="name" class="col-md-4 control-label">Nome </label>
        <div class="col-md-6">
          <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required>
          @if ($errors->has('name'))
            <span class="help-block">
              <strong>{{ $errors->first('name') }}</strong>
            </span>
          @endif
        </div>
      </div>
      <div class="form-group{{ $errors->has('cnpj') ? ' has-error' : '' }}">
        <label for="cpf" class="col-md-4 control-label">CPF </label>
        <div class="col-md-6">
          <input id="cpf" type="text" class="form-control" name="cpf" value="{{ old('cpf') }}" required>
          @if ($errors->has('cpf'))
            <span class="help-block">
              <strong>{{ $errors->first('cpf') }}</strong>
            </span>
          @endif
        </div>
      </div>
      <div class="form-group{{ $errors->has('login') ? ' has-error' : '' }}">
        <label for="login" class="col-md-4 control-label">Login </label>
        <div class="col-md-6">
          <input id="login" type="text" class="form-control" name="login" value="{{ old('login') }}" required>
          @if ($errors->has('login'))
            <span class="help-block">
              <strong>{{ $errors->first('login') }}</strong>
            </span>
          @endif
        </div>
      </div>
      <div class="form-group{{ $errors->has('login') ? ' has-error' : '' }}">
        <label for="email" class="col-md-4 control-label">Email </label>
        <div class="col-md-6">
          <input id="email" type="text" class="form-control" name="email" value="{{ old('email') }}" required>
          @if ($errors->has('email'))
            <span class="help-block">
              <strong>{{ $errors->first('login') }}</strong>
            </span>
          @endif
        </div>
      </div>
      <div class="form-group{{ $errors->has('endereco') ? ' has-error' : '' }}">
        <label for="endereco" class="col-md-4 control-label">Endereco </label>
        <div class="col-md-6">
          <input id="endereco" type="text" class="form-control" name="endereco" value="{{ old('endereco') }}">
          @if ($errors->has('endereco'))
            <span class="help-block">
              <strong>{{ $errors->first('endereco') }}</strong>
            </span>
            @endif
        </div>
      </div>
      @unless ($Empresa->count())
      @else
        <div class="panel panel-semborda">
          <!-- Vincular Empresas no Cadastro de Usuário -->
          <div class="panel-heading">Cadastrar Usuário a Uma Empresa?</div>
          <table class="table table-striped">
            @foreach ($Empresa as $Empresa)
              @php
                $teste = $loop->iteration % 2;
              @endphp
              @if ($teste == 1)
                <tr>
              @endif
                  <td>
                    <input id type="checkbox" name = "empresa_id[{{$Empresa->id}}]" value="{{$Empresa->id}}"> {{$Empresa->name}}
                  </td>
              @if ($teste == 0)
                </tr>
              @endif
            @endforeach
            @if ($teste == 1)
              <td>&nbsp;</td></tr>
            @endif
          </table>
        </div>
      @endunless
      <div class="form-group">
        <div class="col-md-6 col-md-offset-4">
          <button type="submit" class="btn btn-primary">
            <i class="fa fa-save"></i> Salvar
          </button>
        </div>
      </div>
    </form>
  </div>
</div>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.app', ["current" => "users"])
@section('body')
<div class="card border">
  <div class="card-body">
    <form class="form-horizontal" role="form" method="POST" action="{{ route('user.update',$User->id) }}">
      @csrf
      @method('PUT')
      <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
        <label for="name" class="col-md-4 control-label">Nome </label>
        <div class="col-md-6">
          <input id="name" type="text" class="form-control" name="name" value="{{$User->name}}" required>
          @if ($errors->has('name'))
            <span class="help-block">
              <strong>{{ $errors->first('name') }}</strong>
            </span>
          @endif
        </div>
      </div>
      <div class="form-group{{ $errors->has('cnpj') ? ' has-error' : '' }}">
        <label for="cpf" class="col-md-4 control-label">CPF </label>
        <div class="col-md-6">
          <input id="cpf" type="text" class="form-control" name="cpf" value="{{$User->cpf}}" required>
          @if ($errors->has('cpf'))
            <span class="help-block">
              <strong>{{ $errors->first('cpf') }}</strong>
            </span>
          @endif
        </div>
      </div>
      <div class="form-group{{ $errors->has('login') ? ' has-error' : '' }}">
        <label for="login" class="col-md-4 control-label">Login </label>
        <div class="col-md-6">
          <input id="login" type="text" class="form-control" name="login" value="{{$User->login}}" required>
          @if ($errors->has('login'))
            <span class="help-block">
              <strong>{{ $errors->first('login') }}</strong>
            </span>
          @endif
        </div>
      </div>
      <div class="form-group{{ $errors->has('login') ? ' has-error' : '' }}">
        <label for="email" class="col-md-4 control-label">Email </label>
        <div class="col-md-6">
          <input id="email" type="text" class="form-control" name="email" value="{{$User->email}}" required>
          @if ($errors->has('email'))
            <span class="help-block">
              <strong>{{ $errors->first('login') }}</strong>
            </span>
          @endif
        </div>
      </div>
      <div class="form-group{{ $errors->has('endereco') ? ' has-error' : '' }}">
        <label for="endereco" class="col-md-4 control-label">Endereco </label>
        <div class="col-md-6">
          <input id="endereco" type="text" class="form-control" name="endereco" value="{{$User->endereco}}">
          @if ($errors->has('endereco'))
            <span class="help-block">
              <strong>{{ $errors->first('endereco') }}</strong>
            </span>
          @endif
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-6 col-md-offset-4">
          <button type="submit" class="btn btn-primary">
            <i class="fa fa-save"></i> Salvar
          </button>
        </div>
      </div>
    </form>
  </div>
</div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.app', ["current" => "users"])
@section('body')
<div class="card border">
  <div class="card-body">
    <h5 class="card-title">Usuários Cadastrados</h5>
    <div class="table-responsive">
      <table class="table table-ordered table-hover">
        <tr>
          <th>Nome</th>
          <th>CPF</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
        @foreach ($User as $User)
          <tr>
            <td> {{$User->name}}</td>
            <td> {{$User->cpf}}</td>
            <td class="text-center">
              <a href= "{{ route('user.edit',$User->id) }}" class="btn btn-sm">
                Editar</i></a>
            </td>
            <td class="text-center">
              <a href= "{{ route('user.show',$User->id) }}" class="btn btn-sm">
                Informações</i></a>
            </td>
            <td class="text-center">
              {{method_field('DELETE')}}
              <a href= "{{ route('user.destroy',$User->id) }}" value="Delete" class="btn btn-sm">
                Excluir</i></a>
            </td>
          </tr>
        @endforeach
      </table>
      <a class="btn btn-danger" href="{{ route('user.create') }}">Cadastrar Novo Usuário</a>
    </div>
  </div>
</div>

@endsection

resources/views/user/show.blade.php
@extends('layouts.app', ["current" => "users"])

@section('body')
<div class="card border">
  <div class="card-body">
    <h5 class="card-title">Dados do Usuário</h5>
    <form class="form-horizontal" role="form" method="POST" action="#">
      <div class="form-group">
        <label for="user" class="col-md-4 control-label">Nome do Usuário</label>
        <label for="user" class="col-md-6 control-label text-left">{{ $User->name }}</label>
      </div>
      <div class="form-group">
        <label for="nome" class="col-md-4 control-label">CPF</label>
        <label for="nome" class="col-md-6 control-label text-left">{{ $User->cpf }}</label>
      </div>
      <div class="form-group">
        <label for="nome" class="col-md-4 control-label">login</label>
        <label for="nome" class="col-md-6 control-label text-left">{{ $User->login }}</label>
      </div>
      <div class="form-group">
        <label for="nome" class="col-md-4 control-label">email</label>
        <label for="nome" class="col-md-6 control-label text-left">{{ $User->email }}</label>
      </div>
      <div class="form-group">
        <label for="nome" class="col-md-4 control-label">Endereço</label>
        <label for="nome" class="col-md-6 control-label text-left">{{ $User->endereco }}</label>
      </div>
    </form>
  </div>
</div>
@endsection